// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqh7p6DzXlm03BUz_5W1-doqLy2qt1K2g',
    appId: '1:172354942341:web:d4c56a2ae1aa80f50940ec',
    messagingSenderId: '172354942341',
    projectId: 'fanpage-18c44',
    authDomain: 'fanpage-18c44.firebaseapp.com',
    storageBucket: 'fanpage-18c44.appspot.com' ,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbKaNSRVVP5acmTvI9jqbxofxIwmmpa3Y',
    appId: '1:172354942341:android:43b256c637e79c9b0940ec',
    messagingSenderId: '172354942341',
    projectId: 'fanpage-18c44',
    storageBucket: 'fanpage-18c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD84Oy0lEJ73EdFLugsk6YURfC9ki6Cicw',
    appId: '1:172354942341:ios:2abc48c050f9fc040940ec',
    messagingSenderId: '172354942341',
    projectId: 'fanpage-18c44',
    storageBucket: 'fanpage-18c44.appspot.com',
    iosClientId: '172354942341-cnokrsqahl5sf1boq0drelhv31agkold.apps.googleusercontent.com',
    iosBundleId: 'com.example.fanpage',
  );
}
